INSERT INTO BUILDING(ID, NAME) VALUES(1, 'EF');
INSERT INTO BUILDING(ID, NAME) VALUES(2, '158');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(1, 'E110', 1,  2);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(2, 'S221', 2,  1);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'ON', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'OFF', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (3, 7, 'ON', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (4, 0, 'OFF', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (5, 6, 'ON', 2);
